baseURL = "https://lyh0925.com"
languageCode = "en-us"
title = "LYH"
theme = "hugo-ht"
enableRobotsTXT = true
# enableGitInfo = true

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"
posts = "/posts/:year/:month/:day/:slug/"

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Research"
    url = "/en/research/"
    weight = 3
[[menu.cn]]
    name = "English"
    url = "/"
    weight = 3

[params]
    description = "LYH"
    homeText = "Liu Yuhang's Personal Website"
    # Please make sure `blogDirNmae` matches the name used in `menu` above:
    blogDirName = "posts"
    # singleLang = true
    defaultLang = "en"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs" 
    MathJaxVersion = "2.7.5"
    # Edit by yourself:
    GithubEdit = "https://github.com/LYH0925/mywebsite/edit/master/content/"
    copyright = "&copy;"
    copyrightYear = "2024-2025"
    favicon = ""
    GithubRepo = "https://github.com/LYH0925/mywebsite"
    # Edit by yourself:
    ContentSource = "https://raw.githubusercontent.com/LYH0925/mywebsite/master/content/" 

[params.logo]
  # Change the logo picture as your prefer:
  url = ""

[params.lang]

    [params.lang.author]
      en = "Liu Yuhang"
      cn = "刘昱航"

    [params.lang.madeWith]
      en = "Made with"
      cn = "本站驱动"

    [params.lang.edit]
      en = "Suggest an edit of this page"
      cn = "编辑本页"

     [params.lang.lastupdate]
      en = "Last modified on"
      cn = "最后一次修改于"
         
    [params.lang.Sitelastupdate]
      en = "Site last updated on"
      cn = "最近一次更新于"
    
    [params.lang.sourceCode]
      en = "Content in"
      cn = "内容存于"

    [params.lang.subscribe]
      en = "Subscribe"
      cn = "订阅"

    [params.lang.license]
      en = "License"
      cn = "版权"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100
